{
 "title": "JWT Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "user_active{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_success{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_fail{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"all\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"get\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"put\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"post\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"delete\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(purchase_latency{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "request latency"
    }
   ]
  },
  {
   "title": "Pizza sales/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(purchase_sold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purchase_revenue{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "system_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "system_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}